### ISSUE TITLE
Investigate eslint-plugin-i

### ISSUE THREAD

**Issue by 72636c** [seek-oss/eslint-config-seek#110]
This is a contentious fork of `eslint-plugin-import`.

https://www.npmjs.com/package/eslint-plugin-i

**Comment by askoufis** [comment]
FYI the package has been renamed and republished as [`eslint-plugin-import-x`](https://github.com/un-ts/eslint-plugin-import-x). While I respect Mr backwards-compatibility-4-lfy's opinions, I disagree with them, and honestly would like to migrate to this package if we're still open to it.
