### ISSUE TITLE
Warning: React version not specified in eslint-plugin-react settings

### ISSUE THREAD

**Issue by tgdev** [seek-oss/eslint-config-seek#25]
When running `sku lint` I get the above warning.

Looking at [line 31 in the index file of this repo](https://github.com/seek-oss/eslint-config-seek/blob/3b5802a39d74c9cd1dd9a9dfa148a166a8df7bb2/index.js#L31) it appears the version is being set to `>16`.

Looking at the [version util within eslint-react-plugin](https://github.com/yannickcr/eslint-plugin-react/blob/24044e00c0b53e0a6ac939a3a05dfc643fb95adb/lib/util/version.js) I'm not entirely sure our value is valid which is why I'm getting the warning.

There is an option to pass in "detect" as the value for the react version (See line 32 of version util link above). 

eg:

```
settings: {
  react: {
    version: 'detect'
  }
}
```

This might be a better way by linting against the version of react that is installed in a consumers project rather than trying to lint against a specific version (eg: 16.4.0) if consumers of sku decide they want to keep their version of react up to date or just newer than the one specified in this config.

Keen to get others thoughts on this or work with someone on testing this detect option out.

**Comment by 72636c** [comment]
Resolved in https://github.com/seek-oss/eslint-config-seek/releases/tag/v8.0.0
